# Feature Importance Analysis

In [1]:
import pandas as pd

feature_importance = pd.read_csv(
    r"D:\Projects\Delivery_ETA\outputs\feature_importance.csv"
)

feature_importance.head(15)

                               feature  importance
0                        osrm_distance    0.523344
1                            osrm_time    0.244033
2       actual_distance_to_destination    0.102342
3                 corridor_delay_ratio    0.046581
4                           route_type    0.013282
5                   network_risk_score    0.010181
6                  corridor_trip_count    0.006674
7                destination_in_degree    0.006411
8        destination_degree_centrality    0.006141
9   destination_betweenness_centrality    0.005910
10              destination_out_degree    0.005364
11                   distance_per_hour    0.004493
12                    source_in_degree    0.004446
13       source_betweenness_centrality    0.004439
14                           trip_hour    0.003944

In [2]:
top_features = (
    feature_importance
    .head(15)
)

top_features

                               feature  importance
0                        osrm_distance    0.523344
1                            osrm_time    0.244033
2       actual_distance_to_destination    0.102342
3                 corridor_delay_ratio    0.046581
4                           route_type    0.013282
5                   network_risk_score    0.010181
6                  corridor_trip_count    0.006674
7                destination_in_degree    0.006411
8        destination_degree_centrality    0.006141
9   destination_betweenness_centrality    0.005910
10              destination_out_degree    0.005364
11                   distance_per_hour    0.004493
12                    source_in_degree    0.004446
13       source_betweenness_centrality    0.004439
14                           trip_hour    0.003944

In [3]:
top_features = (
    feature_importance
    .head(15)
)

top_features

                               feature  importance
0                        osrm_distance    0.523344
1                            osrm_time    0.244033
2       actual_distance_to_destination    0.102342
3                 corridor_delay_ratio    0.046581
4                           route_type    0.013282
5                   network_risk_score    0.010181
6                  corridor_trip_count    0.006674
7                destination_in_degree    0.006411
8        destination_degree_centrality    0.006141
9   destination_betweenness_centrality    0.005910
10              destination_out_degree    0.005364
11                   distance_per_hour    0.004493
12                    source_in_degree    0.004446
13       source_betweenness_centrality    0.004439
14                           trip_hour    0.003944

In [4]:
graph_features = [
    "corridor_delay_ratio",
    "network_risk_score",
    "source_betweenness_centrality",
    "destination_betweenness_centrality"
]

feature_importance[
    feature_importance["feature"]
    .isin(graph_features)
]

                               feature  importance
3                 corridor_delay_ratio    0.046581
5                   network_risk_score    0.010181
9   destination_betweenness_centrality    0.005910
13       source_betweenness_centrality    0.004439

In [5]:
import pandas as pd

graph_results = pd.DataFrame({
    "Metric": [
        "MAE",
        "RMSE",
        "R2",
        "Accuracy_15pct"
    ],
    "Value": [
        31.49,
        90.92,
        0.9506,
        54.46
    ]
})

graph_results.to_csv(
    r"D:\Projects\Delivery_ETA\outputs\graph_model_results.csv",
    index=False
)

print(graph_results)

           Metric    Value
0             MAE  31.4900
1            RMSE  90.9200
2              R2   0.9506
3  Accuracy_15pct  54.4600

In [6]:
import pandas as pd

feature_importance = pd.read_csv(
    r"D:\Projects\Delivery_ETA\outputs\feature_importance.csv"
)

top_features = feature_importance.head(15)

top_features.to_csv(
    r"D:\Projects\Delivery_ETA\outputs\top_features.csv",
    index=False
)

top_features

                               feature  importance
0                        osrm_distance    0.523344
1                            osrm_time    0.244033
2       actual_distance_to_destination    0.102342
3                 corridor_delay_ratio    0.046581
4                           route_type    0.013282
5                   network_risk_score    0.010181
6                  corridor_trip_count    0.006674
7                destination_in_degree    0.006411
8        destination_degree_centrality    0.006141
9   destination_betweenness_centrality    0.005910
10              destination_out_degree    0.005364
11                   distance_per_hour    0.004493
12                    source_in_degree    0.004446
13       source_betweenness_centrality    0.004439
14                           trip_hour    0.003944

In [7]:
import pandas as pd

print(pd.read_csv(
    r"D:\Projects\Delivery_ETA\outputs\graph_model_results.csv"
))

print()

print(pd.read_csv(
    r"D:\Projects\Delivery_ETA\outputs\top_features.csv"
).head())

           Metric    Value
0             MAE  31.4900
1            RMSE  90.9200
2              R2   0.9506
3  Accuracy_15pct  54.4600

                          feature  importance
0                   osrm_distance    0.523344
1                       osrm_time    0.244033
2  actual_distance_to_destination    0.102342
3            corridor_delay_ratio    0.046581
4                      route_type    0.013282